# Generated by Django 4.1.3 on 2022-11-30 17:03

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('saram', models.IntegerField(max_length=7, verbose_name='Saram')),
                ('graduacao', models.CharField(max_length=100, verbose_name='Posto / Graduação')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor / Seção')),
                ('ramal', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ramal')),
                ('data', models.DateField(default=django.utils.datetime_safe.datetime, verbose_name='Data')),
                ('especificacoes', models.CharField(max_length=100, verbose_name='Especifiações')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observações')),
                ('sinf', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='SINF')),
                ('lacre', models.IntegerField(max_length=7, verbose_name='Ramal')),
                ('bmp', models.IntegerField(max_length=7, verbose_name='BMP')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Quantidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
