# Generated by Django 4.1.3 on 2022-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='bmp',
            field=models.CharField(max_length=10, verbose_name='BMP'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='lacre',
            field=models.CharField(max_length=7, verbose_name='Lacre'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='saram',
            field=models.CharField(max_length=7, verbose_name='Saram'),
        ),
    ]
