# Generated by Django 4.1.3 on 2022-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0002_alter_recibo_bmp_alter_recibo_lacre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
