# Generated by Django 4.1.3 on 2022-12-03 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0004_alter_recibo_data_alter_recibo_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 12, 3), verbose_name='Data'),
        ),
    ]
