# Generated by Django 4.1.3 on 2022-12-05 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0005_alter_recibo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 12, 5), verbose_name='Data'),
        ),
    ]
