# Generated by Django 4.1.3 on 2022-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0006_alter_recibo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='quantidade',
            field=models.IntegerField(max_length=100, verbose_name='Quantidade'),
        ),
    ]
