# Generated by Django 4.1.3 on 2022-12-06 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo_e_cautela', '0007_alter_recibo_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='data',
            field=models.DateField(default=datetime.date(2022, 12, 6), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='observacao',
            field=models.CharField(max_length=100, verbose_name='Observação'),
        ),
    ]
